# Generated by Django 5.2.16 on 2026-07-20 16:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meterId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffVersion',
            fields=[
                ('versionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('effectiveDate', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RESIDENT', 'Resident')], default='RESIDENT', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionReading',
            fields=[
                ('readingId', models.BigAutoField(primary_key=True, serialize=False)),
                ('cumulativeWh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetBudgetSYP', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equivalentLimitKWh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='core.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('isRead', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.meter')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetPushEnabled', models.BooleanField(default=True)),
                ('tierPushEnabled', models.BooleanField(default=True)),
                ('anomalyPushEnabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecastDate', models.DateField()),
                ('predictedConsumptionKWh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualConsumptionKWh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isAnomalous', models.BooleanField(default=False)),
                ('deviationAmountKWh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='core.meter')),
            ],
            options={
                'unique_together': {('meter', 'forecastDate')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycleStartDate', models.DateField()),
                ('predictedMonth1KWh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predictedMonth2KWh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualMonth1KWh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expectedBillSYP', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_forecasts', to='core.meter')),
            ],
            options={
                'unique_together': {('meter', 'cycleStartDate')},
            },
        ),
        migrations.CreateModel(
            name='TariffTier',
            fields=[
                ('tierId', models.BigAutoField(primary_key=True, serialize=False)),
                ('tierNumber', models.IntegerField()),
                ('startKWh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endKWh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricePerKWh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tariffVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.tariffversion')),
            ],
            options={
                'unique_together': {('tariffVersion', 'tierNumber')},
            },
        ),
        migrations.CreateModel(
            name='UserMeterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('isDefault', models.BooleanField(default=False)),
                ('assignedDate', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meter')},
            },
        ),
    ]
