# Generated by Django 5.2.16 on 2026-07-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consumptionreading_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffversion',
            name='isActive',
        ),
    ]
