# Generated by Django 5.2.16 on 2026-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tariffversion_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
