# Generated by Django 5.2.16 on 2026-07-31 19:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_pushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumptionSummary',
            fields=[
                ('summaryId', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('totalKWh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.meter')),
            ],
            options={
                'unique_together': {('meter', 'date')},
            },
        ),
    ]
