# Generated by Django 5.2.16 on 2026-07-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailyconsumptionsummary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consumptionreading',
            index=models.Index(fields=['meter', '-timestamp'], name='reading_meter_time_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyconsumptionsummary',
            index=models.Index(fields=['meter', '-date'], name='summary_meter_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyforecast',
            index=models.Index(fields=['meter', 'forecastDate'], name='forecast_meter_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['meter', '-timestamp'], name='notif_meter_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffversion',
            index=models.Index(fields=['-effectiveDate'], name='tariff_version_date_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeterpreference',
            index=models.Index(fields=['user', 'isDefault'], name='pref_user_default_idx'),
        ),
    ]
