# Generated by Django 5.2.16 on 2026-08-04 16:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consumptionreading_reading_meter_time_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyThreshold',
            fields=[
                ('thresholdId', models.BigAutoField(primary_key=True, serialize=False)),
                ('targetRegionName', models.CharField(default='المنطقة المحلية / سوريا', max_length=100)),
                ('baseMeanKWh', models.DecimalField(decimal_places=2, default=Decimal('10.25'), max_digits=10)),
                ('baseThresholdKWh', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=10)),
                ('targetRegionMeanKWh', models.DecimalField(decimal_places=2, default=Decimal('23.16'), max_digits=10)),
                ('calculatedThresholdKWh', models.DecimalField(decimal_places=2, default=Decimal('15.80'), max_digits=10)),
                ('isActive', models.BooleanField(default=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['isActive', '-updatedAt'], name='threshold_active_idx')],
            },
        ),
    ]
