# Generated by Django 5.2.16 on 2026-08-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_anomalythreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('requestId', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('governorate', models.CharField(max_length=50)),
                ('detailedAddress', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-createdAt'], name='sub_req_status_idx'), models.Index(fields=['phoneNumber', 'status'], name='sub_req_phone_status_idx')],
            },
        ),
    ]
