# Generated by Django 5.2.16 on 2026-08-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscriptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('RESIDENT', 'Resident')], default='RESIDENT', max_length=20),
        ),
    ]
